services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      web:
        condition: service_healthy   # Waits for web app + migrations to finish
    environment:
      RUN_MIGRATIONS: "false"
      TZ: Asia/Kolkata

  web:
    build: .
    image: tempo-erp-app:v1.5.0
    command: uvicorn server:app --host 0.0.0.0 --port 8500
    volumes:
      - .:/app
    expose:
      - "8500"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      RUN_MIGRATIONS: "true"
      TZ: Asia/Kolkata
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8500/')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  worker:
    build: .
    image: tempo-erp-app:v1.5.0
    command: celery -A services.celery_app:celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      RUN_MIGRATIONS: "false"
      TZ: Asia/Kolkata
  beat:
    build: .
    image: tempo-erp-app:v1.5.0
    command: celery -A services.celery_app:celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      RUN_MIGRATIONS: "false"
      TZ: Asia/Kolkata
  
  redis:
    image: redis:7
    expose:
      - "6379"
    environment:
      RUN_MIGRATIONS: "false"
      TZ: Asia/Kolkata