services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TempoInstruments
      POSTGRES_DB: tempo_erp
    ports:
      - "5438:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    network_mode: "host"
    image: tempo-erp-app:v1.0.5
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:TempoInstruments@localhost:5432/tempo_erp

# THIS MUST BE FLUSH LEFT (NO SPACES AT THE START)
volumes:
  postgres_data: