"""release_stage_schema

Revision ID: 02da717d6880
Revises: 3d941816b591
Create Date: 2026-08-11 16:22:37.214763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02da717d6880'
down_revision: Union[str, Sequence[str], None] = '3d941816b591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_headers', sa.Column('tally_guid', sa.String(length=100), nullable=False))
    op.alter_column('order_headers', 'customer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_order_headers_tally_guid'), 'order_headers', ['tally_guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_headers_tally_guid'), table_name='order_headers')
    op.alter_column('order_headers', 'customer_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('order_headers', 'tally_guid')
    # ### end Alembic commands ###
