"""Added stock ledger

Revision ID: 1b0d8c621b1f
Revises: ed4ca1d513e1
Create Date: 2026-07-29 15:53:33.874452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0d8c621b1f'
down_revision: Union[str, Sequence[str], None] = 'ed4ca1d513e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('operator_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_code'], ['items_master.item_code'], ),
    sa.ForeignKeyConstraint(['operator_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activity_logs', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'dispatch_records', 'users', ['operator_email'], ['email'], ondelete='SET NULL')
    op.create_foreign_key(None, 'grn_headers', 'users', ['operator_email'], ['email'])
    op.alter_column('items_master', 'available_stock',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('lead_contacts', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lead_targets', 'snovio_raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('order_items', 'order_acceptance_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('stg_order_items_order_acceptance_id_fkey'), 'stg_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'stg_order_items', 'stg_order_headers', ['order_acceptance_id'], ['order_acceptance_id'], ondelete='CASCADE')
    op.alter_column('users', 'quarterly_order_value_target',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'quarterly_order_value_target',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'stg_order_items', type_='foreignkey')
    op.create_foreign_key(op.f('stg_order_items_order_acceptance_id_fkey'), 'stg_order_items', 'stg_order_headers', ['order_acceptance_id'], ['order_acceptance_id'])
    op.alter_column('order_items', 'order_acceptance_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lead_targets', 'snovio_raw_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('lead_contacts', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('items_master', 'available_stock',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'grn_headers', type_='foreignkey')
    op.drop_constraint(None, 'dispatch_records', type_='foreignkey')
    op.alter_column('activity_logs', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_table('stock_ledger')
    # ### end Alembic commands ###
