"""added_order_tracking_schemas

Revision ID: 232d996033c9
Revises: 289e11ae763e
Create Date: 2026-08-10 12:26:38.919071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232d996033c9'
down_revision: Union[str, Sequence[str], None] = '289e11ae763e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_stages',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expected_duration_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('order_headers',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_acceptance_id', sa.String(length=50), nullable=False),
    sa.Column('order_acceptance_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=20), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('dispatched_through', sa.String(length=100), nullable=True),
    sa.Column('delivery_terms', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_stage_code', sa.String(length=50), server_default='PO_SUBMITTED', nullable=False),
    sa.Column('ordered_by', sa.String(length=255), nullable=True),
    sa.Column('packing_charges', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('freight_charges', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='18.00', nullable=False),
    sa.ForeignKeyConstraint(['current_stage_code'], ['production_stages.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['client_companies.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_headers_current_stage_code'), 'order_headers', ['current_stage_code'], unique=False)
    op.create_index(op.f('ix_order_headers_customer_id'), 'order_headers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_headers_order_acceptance_id'), 'order_headers', ['order_acceptance_id'], unique=True)
    op.create_table('bill_headers',
    sa.Column('bill_num', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('indian_state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_headers.order_id'], ),
    sa.PrimaryKeyConstraint('bill_num')
    )
    op.create_index(op.f('ix_bill_headers_order_id'), 'bill_headers', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('um', sa.String(length=10), nullable=True),
    sa.Column('additional_spec_text', sa.Text(), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), sa.Computed('quantity * rate * (1 - discount_percentage / 100)', persisted=True), nullable=False),
    sa.CheckConstraint('discount_percentage >= 0 AND discount_percentage <= 100', name='order_items_discount_percentage_check'),
    sa.CheckConstraint('quantity > 0', name='order_items_quantity_check'),
    sa.CheckConstraint('rate >= 0', name='order_items_rate_check'),
    sa.ForeignKeyConstraint(['item_code'], ['items_master.item_code'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_headers.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_items_item_code'), 'order_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('production_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=False),
    sa.Column('planned_end', sa.DateTime(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('assigned_team', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='PLANNED', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_end IS NULL OR actual_start IS NULL OR actual_end >= actual_start', name='production_schedule_actual_dates_check'),
    sa.CheckConstraint('planned_end >= planned_start', name='production_schedule_planned_dates_check'),
    sa.ForeignKeyConstraint(['created_by'], ['users.email'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order_headers.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_code'], ['production_stages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_production_schedule_order', 'production_schedules', ['order_id'], unique=False)
    op.create_index('ix_production_schedule_stage_planned_start', 'production_schedules', ['stage_code', 'planned_start'], unique=False)
    op.create_table('production_stage_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('exited_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.email'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order_headers.order_acceptance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_stage_history_current', 'production_stage_history', ['order_id'], unique=False, postgresql_where=sa.text('exited_at IS NULL'))
    op.create_index('idx_production_stage_history_order', 'production_stage_history', ['order_id', 'entered_at'], unique=False)
    op.create_table('bill_items',
    sa.Column('bill_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bill_num', sa.String(length=50), nullable=False),
    sa.Column('order_item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bill_num'], ['bill_headers.bill_num'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_code'], ['items_master.item_code'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.order_item_id'], ),
    sa.PrimaryKeyConstraint('bill_item_id')
    )
    op.create_index(op.f('ix_bill_items_order_item_id'), 'bill_items', ['order_item_id'], unique=False)
    op.alter_column('client_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stg_order_headers', type_='unique')
    op.alter_column('client_companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bill_items_order_item_id'), table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('idx_production_stage_history_order', table_name='production_stage_history')
    op.drop_index('idx_production_stage_history_current', table_name='production_stage_history', postgresql_where=sa.text('exited_at IS NULL'))
    op.drop_table('production_stage_history')
    op.drop_index('ix_production_schedule_stage_planned_start', table_name='production_schedules')
    op.drop_index('ix_production_schedule_order', table_name='production_schedules')
    op.drop_table('production_schedules')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_code'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_bill_headers_order_id'), table_name='bill_headers')
    op.drop_table('bill_headers')
    op.drop_index(op.f('ix_order_headers_order_acceptance_id'), table_name='order_headers')
    op.drop_index(op.f('ix_order_headers_customer_id'), table_name='order_headers')
    op.drop_index(op.f('ix_order_headers_current_stage_code'), table_name='order_headers')
    op.drop_table('order_headers')
    op.drop_table('production_stages')
    # ### end Alembic commands ###
