"""Columns according to tally

Revision ID: 289e11ae763e
Revises: 5920dda45639
Create Date: 2026-08-08 17:00:24.569073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289e11ae763e'
down_revision: Union[str, Sequence[str], None] = '5920dda45639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stg_order_headers', 'payment_terms',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'terms_of_delivery',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('uq_stg_order_headers_tally_guid'), table_name='stg_order_headers')
    op.create_index(op.f('ix_stg_order_headers_tally_guid'), 'stg_order_headers', ['tally_guid'], unique=True)
    op.add_column('stg_order_items', sa.Column('staging_header_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stg_order_items_staging_header_id'), 'stg_order_items', ['staging_header_id'], unique=False)
    op.drop_constraint(op.f('stg_order_items_order_acceptance_id_fkey'), 'stg_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'stg_order_items', 'stg_order_headers', ['staging_header_id'], ['staging_id'], ondelete='CASCADE')
    op.drop_column('stg_order_items', 'order_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_order_items', sa.Column('order_acceptance_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stg_order_items', type_='foreignkey')
    op.create_foreign_key(op.f('stg_order_items_order_acceptance_id_fkey'), 'stg_order_items', 'stg_order_headers', ['order_acceptance_id'], ['order_acceptance_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_stg_order_items_staging_header_id'), table_name='stg_order_items')
    op.drop_column('stg_order_items', 'staging_header_id')
    op.drop_index(op.f('ix_stg_order_headers_tally_guid'), table_name='stg_order_headers')
    op.create_index(op.f('uq_stg_order_headers_tally_guid'), 'stg_order_headers', ['tally_guid'], unique=True)
    op.alter_column('stg_order_headers', 'terms_of_delivery',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'payment_terms',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
