"""imporved_production_history

Revision ID: 3d941816b591
Revises: 232d996033c9
Create Date: 2026-08-10 16:37:18.753386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d941816b591'
down_revision: Union[str, Sequence[str], None] = '232d996033c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_stage_history', sa.Column('stage_code', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'production_stage_history', 'production_stages', ['stage_code'], ['code'], ondelete='RESTRICT')
    op.drop_column('production_stage_history', 'stage')
    op.alter_column('stg_order_headers', 'tally_guid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stg_order_headers', 'tally_guid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('production_stage_history', sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'production_stage_history', type_='foreignkey')
    op.drop_column('production_stage_history', 'stage_code')
    # ### end Alembic commands ###
