"""updated_financial_default

Revision ID: 511aa2e932cf
Revises: a1dfd1155525
Create Date: 2026-09-02 11:15:53.927634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511aa2e932cf'
down_revision: Union[str, Sequence[str], None] = 'a1dfd1155525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'base_model_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default='0.00',
               existing_nullable=False)
    op.alter_column('quotations', 'packing_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default='0.00',
               existing_nullable=True)
    op.alter_column('quotations', 'freight_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default='0.00',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotations', 'freight_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotations', 'packing_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotations', 'base_model_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
