"""TallyConnection

Revision ID: 5920dda45639
Revises: dc13ff4a9eb6
Create Date: 2026-08-08 13:44:33.381300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5920dda45639'
down_revision: Union[str, Sequence[str], None] = 'dc13ff4a9eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stg_order_headers', sa.Column('state_name', sa.String(length=100), nullable=True))
    op.alter_column('stg_order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'purchase_order_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'due_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.add_column('stg_order_items', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=True))
    op.alter_column('stg_order_items', 'due_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stg_order_items', 'due_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('stg_order_items', 'discount_percentage')
    op.alter_column('stg_order_headers', 'due_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'purchase_order_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_column('stg_order_headers', 'state_name')
    # ### end Alembic commands ###
