"""updated_OH

Revision ID: 60ce15c4b614
Revises: ff271b33a62e
Create Date: 2026-08-11 17:38:50.654320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ce15c4b614'
down_revision: Union[str, Sequence[str], None] = 'ff271b33a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order_headers', 'purchase_order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('order_headers', 'purchase_order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order_headers', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order_headers', 'packing_charges',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('order_headers', 'freight_charges',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_headers', 'freight_charges',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('order_headers', 'packing_charges',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('order_headers', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('order_headers', 'purchase_order_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('order_headers', 'purchase_order_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
