"""create_qoutations

Revision ID: 620cfc5f8e9b
Revises: b51fdb41b567
Create Date: 2026-08-04 14:45:58.385081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620cfc5f8e9b'
down_revision: Union[str, Sequence[str], None] = 'b51fdb41b567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_number', sa.String(length=10), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('client_company', sa.String(length=255), nullable=False),
    sa.Column('client_address_line1', sa.String(length=500), nullable=False),
    sa.Column('client_city', sa.String(length=100), nullable=False),
    sa.Column('client_postal_code', sa.String(length=30), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone_number', sa.String(length=15), nullable=False),
    sa.Column('enquiry_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('supply', sa.String(length=255), nullable=False),
    sa.Column('installation', sa.String(length=255), nullable=False),
    sa.Column('freight', sa.String(length=255), nullable=False),
    sa.Column('is_dealer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_special_model', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('special_itinerary', sa.Text(), nullable=True),
    sa.Column('sales_user_name', sa.String(length=255), nullable=False),
    sa.Column('sales_user_email', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_path', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_generated_at'), 'quotations', ['generated_at'], unique=False)
    op.create_index(op.f('ix_quotations_product_name'), 'quotations', ['product_name'], unique=False)
    op.create_index(op.f('ix_quotations_quote_number'), 'quotations', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotations_sales_user_email'), 'quotations', ['sales_user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_sales_user_email'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quote_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_product_name'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_generated_at'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###
