"""bom_appended

Revision ID: 70a9bb4a2c49
Revises: 8eb5c33bdd71
Create Date: 2026-09-17 14:54:58.967567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a9bb4a2c49'
down_revision: Union[str, Sequence[str], None] = '8eb5c33bdd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('revision_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bom_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='Draft', nullable=False),
    sa.Column('output_quantity', sa.Numeric(precision=25, scale=4), server_default='1', nullable=False),
    sa.Column('uom', sa.String(length=20), server_default='NOS', nullable=False),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('output_quantity > 0', name='ck_bom_item_quantity_positive'),
    sa.ForeignKeyConstraint(['item_code'], ['test_items_master.item_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_code', 'revision_no', name='uq_bom_item_revision')
    )
    op.create_index(op.f('ix_bom_headers_item_code'), 'bom_headers', ['item_code'], unique=False)
    op.create_table('bom_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), server_default='NOS', nullable=False),
    sa.Column('scrap_percent', sa.Numeric(precision=7, scale=3), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_bom_component_quantity_positive'),
    sa.CheckConstraint('scrap_percent >= 0', name='ck_bom_component_scrap_non_negative'),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_headers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_code'], ['test_items_master.item_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'line_number', name='uq_bom_component_line')
    )
    op.create_index(op.f('ix_bom_components_bom_id'), 'bom_components', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_components_item_code'), 'bom_components', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bom_components_item_code'), table_name='bom_components')
    op.drop_index(op.f('ix_bom_components_bom_id'), table_name='bom_components')
    op.drop_table('bom_components')
    op.drop_index(op.f('ix_bom_headers_item_code'), table_name='bom_headers')
    op.drop_table('bom_headers')
    # ### end Alembic commands ###
