"""upgrade qoutation schema

Revision ID: 72382d76d692
Revises: cb0b03466543
Create Date: 2026-08-14 14:45:47.146357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72382d76d692'
down_revision: Union[str, Sequence[str], None] = 'cb0b03466543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_change_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quoted_product_name', sa.String(length=255), nullable=False),
    sa.Column('quoted_item_code', sa.String(length=100), nullable=True),
    sa.Column('quoted_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('quoted_rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ordered_product_name', sa.String(length=255), nullable=True),
    sa.Column('ordered_item_code', sa.String(length=100), nullable=True),
    sa.Column('ordered_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('ordered_rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_headers.order_id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_change_snapshots_quotation_id'), 'quotation_change_snapshots', ['quotation_id'], unique=False)
    op.drop_index(op.f('ix_stg_order_items_staging_header_id'), table_name='stg_order_items')
    op.drop_table('stg_order_items')
    op.drop_index(op.f('ix_stg_order_headers_tally_guid'), table_name='stg_order_headers')
    op.drop_table('stg_order_headers')
    op.alter_column('order_headers', 'current_stage_code',
               existing_type=sa.VARCHAR(length=50),
               server_default='PENDING',
               existing_nullable=False)
    op.add_column('quotations', sa.Column('status', sa.String(length=30), server_default='GENERATED', nullable=False))
    op.add_column('quotations', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('changed_at', sa.DateTime(), nullable=True))
    op.add_column('quotations', sa.Column('converted_order_id', sa.BigInteger(), nullable=True))
    op.alter_column('quotations', 'quote_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_quotations_changed_at'), 'quotations', ['changed_at'], unique=False)
    op.create_index(op.f('ix_quotations_completed_at'), 'quotations', ['completed_at'], unique=False)
    op.create_index(op.f('ix_quotations_converted_order_id'), 'quotations', ['converted_order_id'], unique=False)
    op.create_index(op.f('ix_quotations_rejected_at'), 'quotations', ['rejected_at'], unique=False)
    op.create_index(op.f('ix_quotations_resolved_at'), 'quotations', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_foreign_key(None, 'quotations', 'order_headers', ['converted_order_id'], ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_resolved_at'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_rejected_at'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_converted_order_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_completed_at'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_changed_at'), table_name='quotations')
    op.alter_column('quotations', 'quote_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('quotations', 'converted_order_id')
    op.drop_column('quotations', 'changed_at')
    op.drop_column('quotations', 'rejected_at')
    op.drop_column('quotations', 'completed_at')
    op.drop_column('quotations', 'resolved_at')
    op.drop_column('quotations', 'status')
    op.alter_column('order_headers', 'current_stage_code',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'PO_SUBMITTED'::character varying"),
               existing_nullable=False)
    op.create_table('stg_order_headers',
    sa.Column('staging_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_acceptance_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_acceptance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('purchase_order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('billing_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('purchase_order_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dispatched_through', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ordered_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('packing_charges', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('freight_charges', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('18.00'), autoincrement=False, nullable=True),
    sa.Column('buyer_gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('terms_of_delivery', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('grand_total', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tally_guid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('staging_id', name=op.f('stg_order_headers_pkey'))
    )
    op.create_index(op.f('ix_stg_order_headers_tally_guid'), 'stg_order_headers', ['tally_guid'], unique=True)
    op.create_table('stg_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('additional_spec_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hsn_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('staging_header_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staging_header_id'], ['stg_order_headers.staging_id'], name=op.f('stg_order_items_staging_header_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('stg_order_items_pkey'))
    )
    op.create_index(op.f('ix_stg_order_items_staging_header_id'), 'stg_order_items', ['staging_header_id'], unique=False)
    op.drop_index(op.f('ix_quotation_change_snapshots_quotation_id'), table_name='quotation_change_snapshots')
    op.drop_table('quotation_change_snapshots')
    # ### end Alembic commands ###
