"""added_item_tagging

Revision ID: 7f4c8f6cdb1e
Revises: da1fc9b53074
Create Date: 2026-08-26 11:35:03.314138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4c8f6cdb1e'
down_revision: Union[str, Sequence[str], None] = 'da1fc9b53074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_queries', sa.Column('item_code', sa.String(length=100), nullable=True))
    op.add_column('faq_queries', sa.Column('item_group', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_faq_queries_item_code'), 'faq_queries', ['item_code'], unique=False)
    op.create_index(op.f('ix_faq_queries_item_group'), 'faq_queries', ['item_group'], unique=False)
    op.create_foreign_key(None, 'faq_queries', 'items_master', ['item_code'], ['item_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faq_queries', type_='foreignkey')
    op.drop_index(op.f('ix_faq_queries_item_group'), table_name='faq_queries')
    op.drop_index(op.f('ix_faq_queries_item_code'), table_name='faq_queries')
    op.drop_column('faq_queries', 'item_group')
    op.drop_column('faq_queries', 'item_code')
    # ### end Alembic commands ###
