"""added_purchase_schemas

Revision ID: 88063e6fe85d
Revises: 17c846fbcc23
Create Date: 2026-09-03 12:24:58.094945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88063e6fe85d'
down_revision: Union[str, Sequence[str], None] = '17c846fbcc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_bills',
    sa.Column('voucher_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_date', sa.Date(), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('bill_value', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('voucher_number')
    )
    op.create_index(op.f('ix_purchase_bills_party_name'), 'purchase_bills', ['party_name'], unique=False)
    op.create_index(op.f('ix_purchase_bills_place_of_supply'), 'purchase_bills', ['place_of_supply'], unique=False)
    op.create_index(op.f('ix_purchase_bills_purchase_date'), 'purchase_bills', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_purchase_bills_purchase_order_date'), 'purchase_bills', ['purchase_order_date'], unique=False)
    op.create_table('purchase_bill_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('purchase_voucher_number', sa.String(length=100), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=7), nullable=False),
    sa.Column('item_specification', sa.Text(), nullable=True),
    sa.Column('billed_quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_measure', sa.String(length=20), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False),
    sa.CheckConstraint('amount >= 0', name='purchase_bill_item_amount_non_negative'),
    sa.CheckConstraint('billed_quantity > 0', name='purchase_bill_item_quantity_positive'),
    sa.CheckConstraint('rate >= 0', name='purchase_bill_item_rate_non_negative'),
    sa.ForeignKeyConstraint(['item_code'], ['test_items_master.item_code'], ),
    sa.ForeignKeyConstraint(['purchase_voucher_number'], ['purchase_bills.voucher_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_voucher_number', 'line_number', name='uq_purchase_bill_item_line')
    )
    op.create_index(op.f('ix_purchase_bill_items_item_code'), 'purchase_bill_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_purchase_bill_items_purchase_voucher_number'), 'purchase_bill_items', ['purchase_voucher_number'], unique=False)
    op.add_column('grn_headers', sa.Column('purchase_voucher_number', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_grn_headers_purchase_voucher_number'), 'grn_headers', ['purchase_voucher_number'], unique=False)
    op.create_foreign_key(None, 'grn_headers', 'purchase_bills', ['purchase_voucher_number'], ['voucher_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grn_headers', type_='foreignkey')
    op.drop_index(op.f('ix_grn_headers_purchase_voucher_number'), table_name='grn_headers')
    op.drop_column('grn_headers', 'purchase_voucher_number')
    op.drop_index(op.f('ix_purchase_bill_items_purchase_voucher_number'), table_name='purchase_bill_items')
    op.drop_index(op.f('ix_purchase_bill_items_item_code'), table_name='purchase_bill_items')
    op.drop_table('purchase_bill_items')
    op.drop_index(op.f('ix_purchase_bills_purchase_order_date'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_purchase_date'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_place_of_supply'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_party_name'), table_name='purchase_bills')
    op.drop_table('purchase_bills')
    # ### end Alembic commands ###
