"""updated_purchase_trigger

Revision ID: 8eb5c33bdd71
Revises: 88063e6fe85d
Create Date: 2026-09-03 12:46:43.183626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb5c33bdd71'
down_revision: Union[str, Sequence[str], None] = '88063e6fe85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_bills', 'bill_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_bills', sa.Column('bill_value', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
