"""Renamed state colume to indian_state in DispatchRecord

Revision ID: 92d4ab795576
Revises: a3be78aec697
Create Date: 2026-07-31 20:16:41.912349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d4ab795576'
down_revision: Union[str, Sequence[str], None] = 'a3be78aec697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dispatch_records', 'state', new_column_name='indian_state', existing_type=sa.String(length=100), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dispatch_records', 'indian_state', new_column_name='state', existing_type=sa.VARCHAR(length=100), existing_nullable=True)
    # ### end Alembic commands ###
