"""quotation_financial_migration

Revision ID: a1dfd1155525
Revises: 7f4c8f6cdb1e
Create Date: 2026-09-02 10:17:54.285993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dfd1155525'
down_revision: Union[str, Sequence[str], None] = '7f4c8f6cdb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('base_model_price', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'))
    op.add_column('quotations', sa.Column('packing_mode', sa.String(length=20), server_default='INCLUSIVE', nullable=False))
    op.add_column('quotations', sa.Column('packing_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('quotations', sa.Column('freight_mode', sa.String(length=20), server_default='INCLUSIVE', nullable=False))
    op.add_column('quotations', sa.Column('freight_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('quotations', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), server_default='18.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'tax_rate')
    op.drop_column('quotations', 'freight_amount')
    op.drop_column('quotations', 'freight_mode')
    op.drop_column('quotations', 'packing_amount')
    op.drop_column('quotations', 'packing_mode')
    op.drop_column('quotations', 'base_model_price')
    # ### end Alembic commands ###
