"""Added mobile number to transport partners

Revision ID: a3be78aec697
Revises: 1b0d8c621b1f
Create Date: 2026-07-29 17:25:33.218113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3be78aec697'
down_revision: Union[str, Sequence[str], None] = '1b0d8c621b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_partners', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics_partners', 'mobile_number')
    # ### end Alembic commands ###
