"""REmoved special itinerary details

Revision ID: c8f65ac0e527
Revises: 620cfc5f8e9b
Create Date: 2026-08-07 12:05:13.140669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f65ac0e527'
down_revision: Union[str, Sequence[str], None] = '620cfc5f8e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lead_targets', 'cost_per_credit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default='0.015',
               existing_nullable=True)
    op.alter_column('lead_targets', 'snovio_raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotations', 'enquiry_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('quotations', 'special_itinerary')
    op.alter_column('stg_order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'due_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stg_order_headers', 'due_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stg_order_headers', 'order_acceptance_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=True)
    op.add_column('quotations', sa.Column('special_itinerary', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('quotations', 'enquiry_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('lead_targets', 'snovio_raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('lead_targets', 'cost_per_credit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    # ### end Alembic commands ###
