"""scheduling_update

Revision ID: da1fc9b53074
Revises: 72382d76d692
Create Date: 2026-08-17 11:31:37.531328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1fc9b53074'
down_revision: Union[str, Sequence[str], None] = '72382d76d692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_schedules', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_schedules', 'updated_at')
    # ### end Alembic commands ###
