"""upgraded_constraint

Revision ID: f1cc976a6446
Revises: 70a9bb4a2c49
Create Date: 2026-09-22 11:12:17.263889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cc976a6446'
down_revision: Union[str, Sequence[str], None] = '70a9bb4a2c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bom_headers_item_code_fkey'), 'bom_headers', type_='foreignkey')
    op.create_foreign_key(None, 'bom_headers', 'items_master', ['item_code'], ['item_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bom_headers', type_='foreignkey')
    op.create_foreign_key(op.f('bom_headers_item_code_fkey'), 'bom_headers', 'raw_materials', ['item_code'], ['item_code'])
    # ### end Alembic commands ###
