"""upgraded to match tally

Revision ID: ff271b33a62e
Revises: 02da717d6880
Create Date: 2026-08-11 16:29:55.325564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff271b33a62e'
down_revision: Union[str, Sequence[str], None] = '02da717d6880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_headers', sa.Column('tally_customer_code', sa.String(length=100), nullable=True))
    op.add_column('order_headers', sa.Column('buyer_gstin', sa.String(length=15), nullable=True))
    op.add_column('order_headers', sa.Column('destination', sa.Text(), nullable=True))
    op.add_column('order_headers', sa.Column('state_name', sa.String(length=100), nullable=True))
    op.add_column('order_headers', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.add_column('order_headers', sa.Column('grand_total', sa.Numeric(precision=15, scale=2), server_default='0.00', nullable=False))
    op.create_index(op.f('ix_order_headers_tally_customer_code'), 'order_headers', ['tally_customer_code'], unique=False)
    op.add_column('order_items', sa.Column('due_date', sa.Date(), nullable=True))
    op.alter_column('order_items', 'hsn_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'hsn_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('order_items', 'due_date')
    op.drop_index(op.f('ix_order_headers_tally_customer_code'), table_name='order_headers')
    op.drop_column('order_headers', 'grand_total')
    op.drop_column('order_headers', 'tax_amount')
    op.drop_column('order_headers', 'state_name')
    op.drop_column('order_headers', 'destination')
    op.drop_column('order_headers', 'buyer_gstin')
    op.drop_column('order_headers', 'tally_customer_code')
    # ### end Alembic commands ###
